# Generated by Django 4.1.7 on 2023-03-13 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileExtract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(max_length=1, verbose_name='Диапазон выписки')),
                ('file', models.FileField(upload_to='registry_files/')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Registry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(max_length=3, verbose_name='Код оператора')),
                ('range_from', models.IntegerField(max_length=7, verbose_name='Диапазон от')),
                ('range_to', models.IntegerField(max_length=7, verbose_name='Диапазон до')),
                ('capacity', models.IntegerField(verbose_name='Емкость')),
                ('operator', models.CharField(max_length=300, verbose_name='Мобильный опрератор')),
                ('region', models.CharField(max_length=300, verbose_name='Регион')),
                ('inn', models.IntegerField(verbose_name='ИНН')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='num_checker.fileextract', verbose_name='Файл с данными')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
    ]
