# Generated by Django 4.1.7 on 2023-03-13 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('num_checker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileextract',
            name='code',
            field=models.IntegerField(verbose_name='Диапазон выписки'),
        ),
        migrations.AlterField(
            model_name='registry',
            name='code',
            field=models.IntegerField(verbose_name='Код оператора'),
        ),
        migrations.AlterField(
            model_name='registry',
            name='range_from',
            field=models.IntegerField(verbose_name='Диапазон от'),
        ),
        migrations.AlterField(
            model_name='registry',
            name='range_to',
            field=models.IntegerField(verbose_name='Диапазон до'),
        ),
    ]
