# Generated by Django 4.1.7 on 2023-03-14 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('num_checker', '0002_alter_fileextract_code_alter_registry_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileextract',
            name='code',
            field=models.IntegerField(choices=[(3, '3xx'), (4, '4xx'), (8, '8xx'), (9, '9xx')], verbose_name='Диапазон выписки'),
        ),
        migrations.AlterField(
            model_name='fileextract',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='registry',
            name='inn',
            field=models.BigIntegerField(verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='registry',
            name='range_from',
            field=models.BigIntegerField(verbose_name='Диапазон от'),
        ),
        migrations.AlterField(
            model_name='registry',
            name='range_to',
            field=models.BigIntegerField(verbose_name='Диапазон до'),
        ),
    ]
